### ISSUE TITLE
BUG: Fix tab ordering  [was] expertise req: how is the tab ordering, or do we care?

### ISSUE THREAD

**Issue by ElSkunkito** [VertNet/georefcalculator#53]
I'm lazy, i like a healthy tab order to help me be even lazier.

**Comment by tucotuco** [comment]
Tabbing almost works right now. But there are some issues.

Good: the tabs function only on those that are visible.
Not so good: Right now tabbing clears the results. Would like to be able to tab to the results in order to copy them without having to use a mouse.

Here is the preferred tab order with a couple of remarks interjected.

ChoiceLanguage
ChoiceCalcType
ChoiceModel
ChoiceCoordSource
ChoiceCoordSystem

txtT2Dec_Lat
txtT7Lat_MinMM
txtT7Lat_Sec
ChoiceLatDirMM
ChoiceLatDirDMS
txtT2Dec_Long
txtT7Long_MinMM
txtT7Long_Sec
ChoiceLongDirMM
ChoiceLongDirDMS

ChoiceDatum
ChoiceLatPrecision

ChoiceDirection
TextFieldHeading /this isn't showing when nearest degree is chosen on ChoiceDirection/

TextFieldOffset
ChoiceOffsetNSDir
TextFieldOffsetEW
ChoiceOffsetEWDir

TextFieldExtent
TextFieldMeasurementError
ChoiceDistUnits
ChoiceDistancePrecision

TextFieldFullResult

TextFieldFromDistance
ChoiceFromDistUnits 
TextFieldToDistance
ChoiceToDistUnits 

// the order of the scale controls on the ui isn't correct at the moment. They should reflect the tab order below.

TextFieldScaleFromDistance
ChoiceScaleFromDistUnits 
ChoiceScale
TextFieldScaleToDistance
ChoiceScaleToDistUnits

**Comment by ElSkunkito** [comment]
k, how bout this for results
(i filed a new bug on dissappearing)
on tabbing to results, all text is selected.
you can then just ctrl+c

or maybe tab to a button, "copy to clipboard"
or if you want to get fancy, add to new 'results  pane'
results pane is a new text area that collects multiple results which you can select all out of.

basically, i'm lazy, I do not know whats happens to the results.
but I can magine ways to help ppl be lazier in post results gathering, processing.

**Comment by tucotuco** [comment]
Moved comment above to the new tab issue. Created new issue for missing TextFieldHeading. Remaining on this issue is tab order and control order for scale converter, which is so closely related they will both happen at once.

**Comment by ElSkunkito** [comment]
tab ordering fixed.

keeping open pending approval.

_notes-n-guidence req-n-suggestions_
_note_
tab order is setup programmaticly for ease
see new functions
function setupTabOrders()
function setupElementOrder()
file gc.ui.js

_guidance req_
tab order order goes from
  "Distance Precision"
to "button calc"
to 'text field full results"
to "button promote"
note sure if this is correct
please advise

_suggestion_
tab order order goes from
"button promote"
to converter controls

how about if you tab after  "button promote" or whatever the final control for the top is
focus goes back to "calc type"

make a KB short cut of SHIFT + C to get focus into converter controls
and SHIFT + C to get out again to previous control?

commit 7229f3d..905f0db  "layout 3 of ?"

hot potato back to you

**Comment by tucotuco** [comment]
The tab orders look perfect. I would leave everything as is. No KB shortcut to converter controls. 

However, given your proclivity for lazy shortcuts, how about when one hits ENTER or clicks calculate that the results get selected automatically. Makes it instantly ready to copy.

**Comment by ElSkunkito** [comment]
i like the lazy way you think

enabled in commit 6c92881..fc95a7f  "added auto select full results from calc button"

close now?

**Comment by tucotuco** [comment]
Awesome.
